config/routes.rb
require File.expand_path('../../lib/assets/routes_constraints', __FILE__)

Engaccino::Application.routes.draw do

  get 'sessions/new'
  get 'ajax/countries'
  get 'ajax/months'
  get 'ajax/companies'
  get 'ajax/recipients'
  get 'ajax/search'
    
  resources :candidates do
    resources :experiences do
      resources :companies
    end
    resources :educations do
      resources :schools
      resources :degrees do
        resources :degree_types
      end
    end
    resources :professional_skill_candidates do
      resources :professional_skills
    end
    resources :interpersonal_skill_candidates do
      resources :interpersonal_skills
    end
    resources :language_candidates do
      resources :languages
    end
    resources :certificate_candidates do
      resources :certificates
    end
  end
  
  resources :candidates, :experiences, :companies, :educations, :schools, :degree_types, :degrees, :professional_skill_candidates, :professional_skills, 
            :interpersonal_skill_candidates, :interpersonal_skills, :language_candidates, :languages, :certificate_candidates, :certificates
  resources :recruiters
  resources :messages, :search
  resources :sessions, :only => [:new, :create, :destroy]
  
  match 'candidates/refresh',         :to => 'candidates#refresh'
  match 'candidates/index/:act',      :to => 'candidates#index'
  match 'candidates/follow',          :to => 'relationships#create'
  match 'candidates/unfollow',        :to => 'relationships#destroy'
  
  match 'recruiters/refresh',         :to => 'recruiters#refresh'
  match 'recruiters/company_details', :to => 'recruiters#company_details'
  match 'recruiters/index/:act',      :to => 'recruiters#index'
  match 'recruiters/follow',          :to => 'relationships#create'
  match 'recruiters/unfollow',        :to => 'relationships#destroy'
  
  match 'companies/up_picture',       :to => 'companies#up_picture'
  
  match 'messages/conversation',      :to => 'messages#conversation'
  match 'messages/menu_top',          :to => 'messages#menu_top'
  match 'messages/menu_left',         :to => 'messages#menu_left'
  match 'messages/archive',           :to => 'messages#archive'
  match 'messages/card_messages',     :to => 'messages#card_messages'
  
  match 'search/index/:search',       :to => 'search#index'
  match 'search/index',               :to => 'search#index'
  
  match '/candidate_signup',          :to => 'candidates#new'
  match '/recruiter_signup',          :to => 'recruiters#new'
  match '/signin',                    :to => 'sessions#new'
  match '/signout',                   :to => 'sessions#destroy'
  
  match '/tour',                      :to => 'pages#tour'
  match '/pricing',                   :to => 'pages#pricing'
  match '/about',                     :to => 'pages#about'
  match '/contact',                   :to => 'pages#contact'
  
  match '/linkedin_signup',           :to => 'users#linkedin_login'
  match '/users/authenticate_login',  :to => 'users#authenticate_login'
  
  root :to => 'users#index',    :constraints => SingedIn.new(true)
  root :to => 'pages#overview', :constraints => SingedIn.new(false) 
end

app/models/candidate.rb
class Candidate < User
  
  attr_accessible :status, :experiences_attributes, :educations_attributes, :degrees_attributes, :languages_attributes, 
                  :professional_skills_attributes, :interpersonal_skills_attributes, :main_education, :main_experience
  
  has_many :experiences,                    :dependent => :destroy
  has_many :companies,                      :through   => :experiences
  has_many :educations,                     :dependent => :destroy
  has_many :degrees,                        :through   => :educations
  has_many :schools,                        :through   => :educations
  has_many :language_candidates,            :dependent => :destroy
  has_many :languages,                      :through   => :language_candidates
  has_many :certificate_candidates,         :dependent => :destroy
  has_many :certificates,                   :through   => :certificate_candidates
  has_many :professional_skill_candidates,  :dependent => :destroy
  has_many :professional_skills,            :through   => :professional_skill_candidates
  has_many :interpersonal_skill_candidates, :dependent => :destroy
  has_many :interpersonal_skills,           :through   => :interpersonal_skill_candidates
  
  accepts_nested_attributes_for :experiences, :allow_destroy => true,
                                :reject_if => lambda { |attr| attr['company_attributes']['name'].blank? &&
                                                              attr['role'].blank? &&
                                                              attr['start_month'].blank? && attr['start_year'].blank? &&
                                                              attr['end_month'].blank?   && attr['end_year'].blank? }
  accepts_nested_attributes_for :educations, :allow_destroy => true,
                                :reject_if => lambda { |attr| attr['school_attributes']['label'].blank? &&
                                                              attr['degree_attributes']['label'].blank? && 
                                                              attr['degree_attributes']['degree_type_attributes']['label'].blank? && 
                                                              attr['start_month'].blank? && attr['start_year'].blank? &&
                                                              attr['end_month'].blank?   && attr['end_year'].blank? }
                                                              
  accepts_nested_attributes_for :degrees,                 :allow_destroy => true
  accepts_nested_attributes_for :language_candidates,     :allow_destroy => true
  accepts_nested_attributes_for :certificate_candidates,  :allow_destroy => true
  
  validates :status, :inclusion => { :in => [ 'available', 'looking', 'open', 'listening', 'happy' ] }, :presence => true
  
  def timeline_duration
    neither_exp_nor_edu? ? nil : last_event.end_year - first_event.start_year - 1 + (13 - first_event.start_month + last_event.end_month) / 12.0
  end
  
  def experience_duration
    no_exp? ? nil : last_experience.end_year - first_experience.start_year - 1 + (13 - first_experience.start_month + last_experience.end_month) / 12.0
  end
  
  def longest_event
    if exp_and_edu? then longest [longest(educations), longest(experiences)] elsif no_exp_but_edu? then longest(educations) elsif no_edu_but_exp? then longest(experiences) else nil end
  end
  
  def longest(collection)
    collection.sort_by!{ |object| object.duration }.last
  end
  
  def first_event
    if exp_and_edu?
      [first_education, first_experience].sort_by!{ |event| if first_education.start_year == first_experience.start_year then event.start_month else event.start_year end }.first
    else
      if neither_exp_nor_edu? then nil elsif no_exp_but_edu? then first_education elsif no_edu_but_exp? then first_experience end
    end
  end
  
  def first_education
    educations.order('start_year ASC').order('start_month ASC').first
  end
  
  def first_experience
    experiences.order('start_year ASC').order('start_month ASC').first
  end
  
  def last_event
    if exp_and_edu?
      [last_education, last_experience].sort_by!{ |event| if last_education.end_year == last_experience.end_year then event.end_month else event.end_year end }.last
    else
      if neither_exp_nor_edu? then nil elsif no_exp_but_edu? then last_education elsif no_edu_but_exp? then last_experience end
    end
  end
  
  def last_education
    educations.order('end_year ASC').order('end_month ASC').last
  end
  
  def last_experience
    experiences.order('end_year ASC').order('end_month ASC').last
  end
  
  def no_exp?
    experiences.empty?
  end
  
  def no_edu?
    educations.empty?
  end
  
  def neither_exp_nor_edu?
    educations.empty? && experiences.empty?
  end
    
  def no_edu_but_exp?
    educations.empty? && !experiences.empty?
  end
    
  def no_exp_but_edu?
    experiences.empty? && !educations.empty?
  end
    
  def exp_and_edu?
    !experiences.empty? && !educations.empty?
  end
  
  def no_pro_skill?
    professional_skills.empty?
  end
  
  def no_perso_skill?
    interpersonal_skills.empty?
  end
  
  def no_certif?
    certificates.empty?
  end
  
  def no_lang?
    languages.empty?
  end
  
  def no_social?
    facebook_login.empty? && linkedin_login.empty? && twitter_login.empty?
  end
end

# == Schema Information
#
# Table name: users
#
#  id                 :integer(4)      not null, primary key
#  first_name         :string(255)
#  last_name          :string(255)
#  city               :string(255)
#  country            :string(255)
#  nationality        :string(255)
#  year_of_birth      :integer(4)
#  phone              :string(255)
#  email              :string(255)
#  facebook_login     :string(255)
#  linkedin_login     :string(255)
#  twitter_login      :string(255)
#  status             :string(255)
#  type               :string(255)
#  facebook_connect   :boolean(1)      default(FALSE)
#  linkedin_connect   :boolean(1)      default(FALSE)
#  twitter_connect    :boolean(1)      default(FALSE)
#  profile_completion :integer(4)      default(0)
#  admin              :boolean(1)      default(FALSE)
#  salt               :string(255)
#  encrypted_password :string(255)
#  created_at         :datetime        not null
#  updated_at         :datetime        not null
#  image              :string(255)
#  main_education     :integer(4)
#  main_experience    :integer(4)
#  quote              :string(255)
#  company_id         :integer(4)
#

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  include TimelineHelper
  
  respond_to :html, :json, :js
  
  before_filter :authenticate,           :except => [:new, :create]
  before_filter :new_user,               :only   => [:new, :create]
  before_filter :authorized, :signed_up, :only   => [:index, :show]
  before_filter :correct_user,           :only   => [:edit, :update]
  before_filter :not_signed_up,          :only   => :edit
  before_filter :admin_user,             :only   => :destroy
  
  def index
    case params[:act]
    when 'following'
      @candidates = current_user.followed_users.where(:type => 'candidate').paginate :page => params[:page], :per_page => 9
    when 'followers'
      @candidates = current_user.followers.where(:type => 'candidate').paginate :page => params[:page], :per_page => 9
    else
      @candidates = Candidate.paginate :page => params[:page], :per_page => 9
    end
    init_page :title => 'candidates.index.title', :javascripts => 'users/index'
    respond_to do |format|
      format.html
      format.js { render :partial => 'candidates' }
    end
  end
  
  def show
    @candidate = Candidate.find params[:id]
    @message = Message.new
    @messages = current_user.messages.where("author_id=#{params[:id]} OR recipient_id=#{params[:id]}").order("created_at DESC").limit(5)
    @title = "#{@candidate.first_name} #{@candidate.last_name}"
    init_page :javascripts => 'candidates/show relationships'
  end
  
  def new
    @candidate = Candidate.new
    init_page :title => 'candidates.new.title'
  end
  
  def create
    @candidate = Candidate.new params[:candidate]
    unless @candidate.save
      render_page :new, :title => 'candidates.new.title'
    else
      sign_in @candidate
      build_education ; build_experience
      render_page :edit, :id => @candidate, :title => 'candidates.edit.complete_your_profile', :javascripts => 'candidates/edit'
    end
  end
  
  def edit
    @candidate = Candidate.find params[:id]
    build_education ; build_experience
    init_page :title => 'candidates.edit.complete_your_profile', :javascripts => 'candidates/edit'
  end

  def update
    @candidate = Candidate.find params[:id]
    unless @candidate.update_attributes params[:candidate]
      init_page :title => 'candidates.edit.complete_your_profile', :javascripts => 'candidates/edit'
      build_education ; build_experience
      respond_to do |format|
        format.js   { render :json => error_messages(@candidate) } if remotipart_submitted?
        format.html { render_page :edit, :id => @candidate }
        format.json { respond_with_bip @candidate }
      end
    else
      associate_schools_and_degrees
      respond_to do |format|
        format.js   { render :json => 'success!' } if remotipart_submitted?
        format.html { @candidate.update_attributes :profile_completion => 5 ; redirect_to @candidate }
        format.json { respond_with_bip @candidate }
      end
    end
  end 

  def destroy
   Candidate.find(params[:id]).destroy
   redirect_to candidates_path, :flash => { :success => t('flash.success.user_destroyed') }
  end
  
  def refresh
    partial = params[:model].nil? ? "candidates/#{params[:partial]}" : "candidates/show_#{params[:model].to_s}s"
    render :partial => partial, :locals => { :candidate => current_user }
  end    
end

app/helpers/candidates_helper.rb
module CandidatesHelper  
  
  def status_options_hash
    { t('candidates.available_status') => :available, 
      t('candidates.looking_status')   => :looking, 
      t('candidates.open_status')      => :open, 
      t('candidates.listening_status') => :listening, 
      t('candidates.happy_status')     => :happy }
  end
  
  def status_options_array
    [ [ 'available', t('candidates.available_status') ],
      [ 'looking',   t('candidates.looking_status') ], 
      [ 'open',      t('candidates.open_status') ],
      [ 'listening', t('candidates.listening_status') ], 
      [ 'happy',     t('candidates.happy_status') ] ]
  end
  
  def month_hash
    { 1 => t('months.january'),   2 => t('months.february'), 3 => t('months.march'),     4 => t('months.april'),
      5 => t('months.may'),       6 => t('months.june'),     7 => t('months.july'),      8 => t('months.august'),
      9 => t('months.september'), 10 => t('months.october'), 11 => t('months.november'), 12 => t('months.december') } 
  end
  
  def main_experience_options(candidate)
    candidate.experiences.map { |experience| role = experience.role ; [ experience.id, "#{role.slice(0..29)}#{'...' if role.length > 30}" ] }
  end
  
  def main_education_options(candidate)
    candidate.educations.map { |education| label = education.degree.degree_type.label.split('(')[0] ; [ education.id, "#{label.slice(0..13)}#{'..' if label.length > 14}" ] }
  end
end

app/views/candidates/_candidate_degree.haml
= Education.find(candidate.main_education).degree.label

app/views/candidates/_experience_fields.html.erb
<div class="fields">
  <br />
  <%= f.fields_for :company do |company_builder| render 'company_fields', :f => company_builder end %>
  <%= f.text_field :role,        :id => 'role',        :class => 'field margin_right' %>
  <%=t 'from' %>
  <%= f.select :start_month, (1..12).map {|m| [t('date.month_names')[m], m]}, {:prompt => t('candidates.experience.start_month')}, :class => 'select' %>  
  <%= f.select :start_year, (1930..Time.now.year).to_a.reverse.map {|m| [m,m]}, {:prompt => t('candidates.experience.start_year')}, :class => 'select' %>                                    
  <%=t 'to' %>
  <%= f.select :end_month, (1..12).map {|m| [t('date.month_names')[m], m]}, {:prompt => t('candidates.experience.end_month')}, :class => 'select' %>
  <%= f.select :end_year, (1930..Time.now.year).to_a.reverse.map {|m| [m,m]}, {:prompt => t('candidates.experience.end_year')}, :class => 'select' %>
  <%= link_to_delete '-', f, t('candidates.experience.delete') %>
</div>

app/views/candidates/_import.html.erb
<div class="white_block">
	<div class="left margin_right">
	  <%=t 'candidates.edit.speed_up_by_import' %>
	</div>
	<div class="left">
	  <%= link_to "#{t('candidates.edit.import_from')} LinkedIn", '#', :class => 'button grey_gradient big margin_right slightly_round left' %>
	  <%= link_to "#{t('candidates.edit.import_from')} Facebook", '#', :class => 'button grey_gradient big slightly_round right' %>
	</div>
	<br /><br /><br />
</div>

app/views/candidates/_new_social_connect.haml
%h2
  = t('candidates.new.or_use_social_connect')
  
= link_to "#{t('candidates.new.connect_via')} Linkedin", linkedin_signup_path, :class => 'grey_gradient button', :id => 'facebook_connect'
= link_to "#{t('candidates.new.connect_via')} Twitter", '#',  :class => 'grey_gradient button'

app/views/candidates/_personal_information.html.erb
<div id="personal_information" class="white_block">
  <h2><%=t "candidates.personal_information" %></h2>
  <%= f.text_field :first_name,    :id => 'first_name', :class => 'field' %><br />
  <%= f.text_field :last_name,     :id => 'last_name', :class => 'field' %><br />
  <%= f.text_field :year_of_birth, :id => 'year_of_birth', :class => 'field' %><br />
  <%= f.text_field :country,       :id => 'country', :class => 'field' %>
</div>

app/views/candidates/_resume_educations.html.erb
<h1>EDUCATION</h1>
<% unless @educations.empty? %>
  <% @educations.order("start_year ASC").order("start_month ASC").each do |education| %>
  	<table id='education_block_<%= education.id %>'>
  	  <%= render 'resume_education_block', :education => education, :candidate => candidate %>
  	</table>
  <% end %>  
<% end %>

app/views/candidates/_resume_share_edit.html.erb
<div id="share_edit">
  <%= link_to t('candidates.show.share_profile'), '#', :class => 'slightly_round blue button' %>
  <%= link_to t('candidates.show.edit_profile'), edit_candidate_path(candidate), :class => 'slightly_round grey button margin_right' %>
  <div id="completion_container" class="slightly_round">
    <div id="completion_bar_empty" class="slightly_round">
      <div id="completion_bar_full" class="slightly_round" style="width: <%= 3*candidate.profile_completion %>px;"></div>
    </div>
    Your profile is <%= candidate.profile_completion %>% complete<%= link_to "What's missing?", '#' %>
  </div>
</div>

app/views/candidates/_resume_timeline.html.erb
<% unless candidate.timeline_duration.nil? %>

  <% units = { :x => 100 / candidate.timeline_duration, :y => 150 / candidate.longest_event.duration } %>
  <% height = (candidate.longest_event.duration * units[:y] * 1.7).round %>
  <% axis = candidate.long_timeline? ? design_axis_w_decades(candidate, units) : design_axis(candidate, units) %>

  <div id="timeline" style="height: <%= height+55 %>px;">
    <h1>TIMELINE</h1>
    <div class="timeline_container" style="height: <%= height %>px;">
      <div class="events">
        <% [candidate.educations, candidate.experiences].each do |collection| %>
          <% collection.each do |object| %>
            <% block = design_block(object, collection, units) %>
            <div class="<%= object.class.name.downcase %>_block" style="height:<%= block[:height] %>px; width:<%= block[:width] %>%; left:<%= block[:left] %>%; z-index: <%= block[:z_index] %>;">
              <div class="shade" style="opacity:<%= block[:shade] %>;"></div>
              <% unless block[:label][:type] == 'vertical' %><div class="<%= block[:label][:type] %> label"><%= block[:label][:text] %></div><% end %>
            </div>
            <% if block[:label][:type] == 'vertical' %>
              <div class="vertical_label" style="left:<%= block[:label][:left]+0.9 %>%; z-index: <%= block[:z_index] %>;"><%= block[:label][:text] %></div>
              <div class="vertical_line" style="left:<%= block[:label][:left] %>%; height:<%= height - block[:height] %>px;"></div>
            <% end %>
          <% end %>
        <% end %>
      </div>
      <div class="horizontal_axis" style="width: <%= axis[:width] %>%;">
        <span class="unit_mark" style="width:<%= axis[:first_unit_mark] %>%;"><%= unit_mark_label(candidate, :first) if first_unit_mark?(candidate) %></span>
        <% axis[:unit_marks].times do |n| %>
          <span class="unit_mark" style="left:<%= axis[:first_unit_mark]+n*axis[:unit_mark] %>%; width:<%= axis[:unit_mark] %>%;"><%= unit_mark_label(candidate, :normal, n) %></span>
        <% end %>
        <% if last_unit_mark?(candidate) %>
          <span class="unit_mark" style="left: <%= axis[:first_unit_mark]+(axis[:unit_marks])*axis[:unit_mark] %>%; width:<%= axis[:last_unit_mark] %>%; border:0;"><%= unit_mark_label(candidate, :last) %></span>
        <% end %>
      </div>
    </div>
  </div>
  
<% else %>

  <div id="timeline">
    <h1>TIMELINE</h1>
    <br />
  </div>

<% end %>

app/views/candidates/_show_education.html.erb
<div <%= if current_user == candidate then "id='show_education_#{education.id}' class='show_education'" end %>>
  <div class="ee_date">
    <h2><%= "#{education.start_month}/#{education.start_year} - #{education.end_month}/#{education.end_year}" %></h2>
  </div>
  <div class="ee_details">
    <h2><%= education.degree.degree_type.label %>, <%= education.degree.label %></h2>
    <%= education.school.name %>
    <p><% if current_user == @candidate && (education.description.nil? || education.description.empty?) %>
      <span class='default'><%= t('candidates.experience.edit_description') %></span>
    <% else %>
      <%= education.description %>
    <% end %>
    </p>
  </div>
</div>
<% if current_user == @candidate %>
  <div id='edit_education_<%= education.id %>' class='hidden edit_education'>
    <%= render 'educations/edit_form', :education => education %>
  </div>
<%end %>

app/views/candidates/_show_experiences.erb
<% @experiences = candidate.experiences.order('start_year DESC, start_month DESC') %>
<h1>
  <%= t('experiences.title').remove_accents.upcase %>
  <%= link_to_function "#{t('add').upcase} +", "showForm('experience', ['show_top','show_timeline', 'candidate'])",
                       :id => 'link_add_experience', :class => "add_link #{' red underline' if @experiences.empty?}" if candidate == current_user %>
  <div class='loader' id='experience_loader'><%= image_tag "loader.gif" %></div>
</h1>
<div id='new_experience' class='hidden'></div> 
<% unless @experiences.empty? %>
  <% @experiences.order('start_year ASC').order('start_month ASC').each do |experience| %>
    <div id='experience_<%= experience.id %>'>
   	  <%= render 'experiences/show', :experience => experience %>
   	  <br/>
   	</div>
  <% end %>
<% else %>
  <div class='add_some'><%=t 'experiences.add_some' %></div>
<% end %>

app/views/candidates/_show_resume.haml
- unless candidate.neither_exp_nor_edu? && candidate != current_user
  #show_timeline
    = render 'show_timeline', :candidate => candidate
- unless candidate.no_pro_skill? && candidate != current_user
  #professional_skill_candidates.block
    = render 'show_professional_skill_candidates', :candidate => candidate
- unless candidate.no_perso_skill? && candidate != current_user
  #interpersonal_skill_candidates.block
    = render 'show_interpersonal_skill_candidates', :candidate => candidate
- unless candidate.no_exp? && candidate != current_user
  #experiences.block
    = render 'show_experiences', :candidate => candidate
- unless candidate.no_edu? && candidate != current_user
  #educations.block
    = render 'show_educations', :candidate => candidate
- unless candidate.no_certif? && candidate != current_user
  #certificate_candidates.small_block
    = render 'show_certificate_candidates', :candidate => candidate
- unless candidate.no_lang? && candidate != current_user
  #language_candidates.small_block
    = render 'show_language_candidates', :candidate => candidate

app/views/candidates/_show_timeline.haml
- unless timeline_duration(candidate).nil?

  - units = { :x => 100 / timeline_duration(candidate), :y => 150 / candidate.longest_event.duration }
  - height = (candidate.longest_event.duration * units[:y] * 1.7).round
  - axis = long_timeline?(candidate) ? design_axis_w_decades(candidate, units) : design_axis(candidate, units)
  
  #timeline{ :style => "height: #{height+55}px;" }
    #show_top_loader.loader
      = image_tag 'loader.gif'
    %h1
      = t('candidates.show.timeline.title').remove_accents.upcase
	  
    .timeline_container{ :style => "height: #{height}px;"}
      .events
        - [candidate.educations, candidate.experiences].each do |collection|
          - collection.each do |object|
            - block = design_block(object, collection, units)
            %div{ :class => "#{object.class.name.downcase}_block", :style => "height: #{block[:height]}px; width: #{block[:width]}%; left: #{block[:left]}%; z-index: #{block[:z_index]};"}
              .shade{ :style => "opacity: #{block[:shade]};"}
              - unless block[:label][:type] == 'vertical'
                .label{ :class => block[:label][:type]}
                  = block[:label][:text]
            - if block[:label][:type] == 'vertical'
              .vertical_label{ :style => "left: #{block[:label][:left]+0.9}%; z-index: #{block[:z_index]};" }
                = block[:label][:text]
              .vertical_line{ :style => "left: #{block[:label][:left]}%; height: #{height - block[:height]}px;"}

      .horizontal_axis{ :style => "width: #{axis[:width]}%;" }
        %span.unit_mark{ :style => "width: #{axis[:first_unit_mark]}%;" }
          = unit_mark_label(candidate, :first) if first_unit_mark?(candidate)
        - axis[:unit_marks].times do |n|
          %span.unit_mark{ :style => "left: #{axis[:first_unit_mark]+n*axis[:unit_mark]}%; width: #{axis[:unit_mark]}%;" }
            = unit_mark_label(candidate, :normal, n)
        - if last_unit_mark?(candidate)
          %span.unit_mark{ :style => "left: #{axis[:first_unit_mark]+(axis[:unit_marks])*axis[:unit_mark]}%; width: #{axis[:last_unit_mark]}%; border:0;" }
            = unit_mark_label(candidate, :last)
- else
  #timeline.example
    %h1
      = t('candidates.show.timeline.title').remove_accents.upcase
    .add_some
      = t('candidates.show.timeline.add')

app/views/candidates/_signup_education.haml
#education.white_block
  %h2
    = t('educations.title')
  = f.fields_for :educations do |education_builder| render 'fields_education', :f => education_builder end
  = link_to_add '+', f, :educations, t('educations.add')
  %br/

app/views/candidates/_signup_personal_information.html.erb
<div id="personal_information" class="white_block">
  <h2><%=t "candidates.personal_information" %></h2>
  <%= f.text_field :first_name,        :value => (!params[:candidate].nil? && !params[:candidate][:first_name].nil? && !params[:candidate][:first_name].empty?) ? params[:candidate][:first_name] : t('candidates.first_name'),
                                       :id => 'first_name', :class => 'field' %><br />
  <%= f.text_field :last_name,         :value => (!params[:candidate].nil? && !params[:candidate][:last_name].nil? && !params[:candidate][:last_name].empty?) ? params[:candidate][:last_name] : t('candidates.last_name'),
                                       :id => 'last_name', :class => 'field' %><br />
  <%= f.text_field :year_of_birth,     :value => (!params[:candidate].nil? && !params[:candidate][:year_of_birth].nil? && !params[:candidate][:year_of_birth].empty?) ? params[:candidate][:year_of_birth] : t('candidates.year_of_birth'),
                                       :id => 'year_of_birth', :class => 'field' %><br />
  <%= f.text_field :country,           :value => (!params[:candidate].nil? && !params[:candidate][:country].nil? && !params[:candidate][:country].empty?) ? params[:candidate][:country] :  t('candidates.country'),
                                       :id => 'country', :class => 'field' %>
</div>