config/routes.rb
require File.expand_path('../../lib/assets/routes_constraints', __FILE__)

Engaccino::Application.routes.draw do

  get 'sessions/new'
  get 'ajax/countries'
  get 'ajax/months'
  get 'ajax/companies'
  get 'ajax/recipients'
  get 'ajax/search'
    
  resources :candidates do
    resources :experiences do
      resources :companies
    end
    resources :educations do
      resources :schools
      resources :degrees do
        resources :degree_types
      end
    end
    resources :professional_skill_candidates do
      resources :professional_skills
    end
    resources :interpersonal_skill_candidates do
      resources :interpersonal_skills
    end
    resources :language_candidates do
      resources :languages
    end
    resources :certificate_candidates do
      resources :certificates
    end
  end
  
  resources :candidates, :experiences, :companies, :educations, :schools, :degree_types, :degrees, :professional_skill_candidates, :professional_skills, 
            :interpersonal_skill_candidates, :interpersonal_skills, :language_candidates, :languages, :certificate_candidates, :certificates
  resources :recruiters
  resources :messages, :search
  resources :sessions, :only => [:new, :create, :destroy]
  
  match 'candidates/refresh',         :to => 'candidates#refresh'
  match 'candidates/index/:act',      :to => 'candidates#index'
  match 'candidates/follow',          :to => 'relationships#create'
  match 'candidates/unfollow',        :to => 'relationships#destroy'
  
  match 'recruiters/refresh',         :to => 'recruiters#refresh'
  match 'recruiters/company_details', :to => 'recruiters#company_details'
  match 'recruiters/index/:act',      :to => 'recruiters#index'
  match 'recruiters/follow',          :to => 'relationships#create'
  match 'recruiters/unfollow',        :to => 'relationships#destroy'
  
  match 'companies/up_picture',       :to => 'companies#up_picture'
  
  match 'messages/conversation',      :to => 'messages#conversation'
  match 'messages/menu_top',          :to => 'messages#menu_top'
  match 'messages/menu_left',         :to => 'messages#menu_left'
  match 'messages/archive',           :to => 'messages#archive'
  match 'messages/card_messages',     :to => 'messages#card_messages'
  
  match 'search/index/:search',       :to => 'search#index'
  match 'search/index',               :to => 'search#index'
  
  match '/candidate_signup',          :to => 'candidates#new'
  match '/recruiter_signup',          :to => 'recruiters#new'
  match '/signin',                    :to => 'sessions#new'
  match '/signout',                   :to => 'sessions#destroy'
  
  match '/tour',                      :to => 'pages#tour'
  match '/pricing',                   :to => 'pages#pricing'
  match '/about',                     :to => 'pages#about'
  match '/contact',                   :to => 'pages#contact'
  
  match '/linkedin_signup',           :to => 'users#linkedin_login'
  match '/users/authenticate_login',  :to => 'users#authenticate_login'
  
  root :to => 'users#index',    :constraints => SingedIn.new(true)
  root :to => 'pages#overview', :constraints => SingedIn.new(false) 
end

app/models/company.rb
class Company < ActiveRecord::Base
  
  attr_accessible :name, :address, :zip, :city, :country, :phone, :email, :url, :image, :about, :recruiter_agency
  
  has_many :experiences, :dependent => :destroy
  has_many :candidates,  :through => :experiences
  has_many :recruiters
  
  countries_array = Country.all.collect { |c| c[0] }
  
  validates :name,              :length       => { :maximum => 80 },                                :presence    => true
  validates :city,              :length       => { :maximum =>  80 },                               :allow_blank => true
  validates :country,           :inclusion    => { :in => countries_array },                        :allow_blank => true
  validates :address,           :length       => { :maximum => 160 },                               :allow_blank => true
  validates :about,             :length       => { :within => 20..160 },                            :allow_blank => true
  validates :url,               :url_format   => true,                                              :allow_blank => true
  validates :email,             :email_format => true, :uniqueness => { :case_sensitive => false }, :allow_blank => true
  validates :phone,             :phone_format => true, :length     => { :within => 7..20 },         :allow_blank => true
  validates :zip,               :length       => { :maximum =>  10 },                               :allow_blank => true
  validates :recruiter_agency,  :inclusion    => { :in => [true,false] }
    
  mount_uploader :image, CompanyImageUploader
    
  def no_about?
    about.nil? || about.empty?
  end
  
  def no_contact_info?
    (url.nil? || url.empty?) && (email.nil? || email.empty?) && (phone.nil? || phone.empty?)
  end
end

# == Schema Information
#
# Table name: companies
#
#  id               :integer(4)      not null, primary key
#  name             :string(255)
#  address          :string(255)
#  city             :string(255)
#  country          :string(255)
#  phone            :string(255)
#  email            :string(255)
#  url              :string(255)
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#  image            :string(255)
#  zip              :string(255)
#  about            :string(255)
#  recruiter_agency :boolean(1)      default(FALSE)
#

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  
  respond_to :html, :json
  
  before_filter :authenticate
  before_filter :authorized, :signed_up, :only => [:show]
  
  def show
    @company  = Company.find params[:id]
    @title    = @company.name
    init_page :javascripts => 'companies/show'
  end
  
  def update
    @company = Company.find params[:id]
    unless @company.update_attributes params[:company]
      respond_to { |format| format.js { render :json => error_messages(@candidate) } if remotipart_submitted? }  
    else
      respond_to do |format|
        format.js   { render :json => 'success!' } if remotipart_submitted?
        format.json { respond_with_bip @company }
      end
    end    
  end
  
  def up_picture
    @company  = Company.find params[:id]
    render :partial => "companies/up_picture"
  end  
end

app/views/companies/_company.haml
.card{ :id => "company_#{company.id}" }
  #company_loader.loader
    = image_tag 'loader.gif'
  
  .company.identity.block
  
    - if current_user_company_profile?
      #image_edit.image_hover
      = form_for company, :remote => true, :html => { :id => 'image_form', :multipart => true } do |f|
        = f.file_field :image,  :id => 'image_button', :class => 'image_button'
        = f.submit     :submit, :class => 'hidden'
        #company_picture_upload_error.hidden.error_messages

    #profile_picture.default.image{ :class => "#{'color-'+rand(1..4).to_s if company.image_url.nil?}" } 
      = image_tag (company.image_url.nil? ? 'default_company.png' : company.image_url(:profile).to_s)

    - if current_user_company_profile?
      .title
        = best_in_place company, :name, :html_attrs => { :class => 'field' }
      .subtitle
        = best_in_place company, :city,    :nil => "#{t('companies.city').downcase}", :html_attrs => { :class => 'field' }
        ,
        = best_in_place company, :country, :nil => "#{t('companies.country').downcase}#{t('_:')}", :html_attrs => { :class => 'field' }
    - else
      = link_to company.name, company_path(company), :class => 'title'
      .subtitle
        = "#{company.city}, #{company.country}"
    
    - if current_user.admin
      - link_to image('trash', t('delete')), company, :method => :delete, :id => "destroy_company_#{company.id}", :class => 'hidden', :confirm => "#{t('companies.destroy.title')} #{company.name}#{t('_?')}", :title => "#{t('companies.destroy.title')} #{company.name}"
  
  - unless company.no_about? && !current_user_company_profile?
    .about.block
      %h2
        = t('companies.about').remove_accents.upcase
      %p
        = best_in_place_if current_user_company_profile?, company, :about, :type => 'textarea', :nil => t('companies.about_nil'), :html_attrs => { :class => 'textarea' }
  
  = render 'companies/show_contact_info', :company => company

app/views/companies/_show_contact_info.haml
.contact_info.block
  %h2
    = t('companies.contact_info').remove_accents.upcase
  - unless company.no_contact_info?
    
    %p
      - if current_user_company_profile?
        = best_in_place company, :url, :nil => "#{t('companies.url').downcase}#{t('_:')}", :html_attrs => { :class => 'field' }
      - else
        = link_to company.url, "http://#{company.url}", :target => '_blank'
    %p
      = best_in_place_if current_user_company_profile?, company, :email,   :nil => "#{t('companies.email').downcase}#{t('_:')}",   :html_attrs => { :class => 'field' }
    %p
      = best_in_place_if current_user_company_profile?, company, :phone,   :nil => "#{t('companies.phone').downcase}#{t('_:')}",   :html_attrs => { :class => 'field' }
    %p
      = best_in_place_if current_user_company_profile?, company, :address, :nil => "#{t('companies.address').downcase}#{t('_:')}", :html_attrs => { :class => 'field' }
  - else
    No information about the company

app/views/companies/_show_recruiters.haml
#company_recruiters
  %h4 #{t('companies.recruiters')} (#{@company.recruiters.count})
  - @company.recruiters.each do |recruiter|
    = render 'recruiters/recruiter', :recruiter => recruiter

app/views/companies/_up_picture.haml
= image_tag @company.image_url(:profile).to_s unless @company.image_url.nil?

app/views/companies/show.haml
= render 'company', :company => @company
= render 'show_recruiters'